
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR DECLARATION ENDLINE EQUAL IDENTIFIER METHOD NUMBERdeclaration : IDENTIFIER EQUAL NUMBER ENDLINE'
    
_lr_action_items = {'IDENTIFIER':([0,],[2,]),'$end':([1,5,],[0,-1,]),'EQUAL':([2,],[3,]),'NUMBER':([3,],[4,]),'ENDLINE':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> IDENTIFIER EQUAL NUMBER ENDLINE','declaration',4,'p_declaration','natparse.py',6),
]
